{% set name = "selinux" %}
{% set version = "0.3.0" %}


package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/selinux-{{ version }}.tar.gz
  sha256: 2a88b337ac46ad0f06f557b2806c3df62421972f766673dd8bf26732fb75a9ea

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
    - setuptools
  run:
    - distro >=1.3.0
    - python >={{ python_min }}
    - setuptools >=39.0

test:
  imports:
    - selinux
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pycontribs/selinux
  summary: shim selinux module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
